name: Latest YouTube Videos
on:
  schedule:
     # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: imparthgalani/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCs8YuffktnbeZiHfPwQ2A9g"
          custom_tags: "videoId/yt:videoId/"
          max_post_count: 6
          template: "<tr><td><a href=\"$url\"><img width=\"140px\" src=\"https://i.ytimg.com/vi/$videoId/mqdefault.jpg\"></a></td>$newline<td><a href=\"$url\">$title</a><br/>$date</td></tr>$newline"
          committer_email: "pgalani193@rku.ac.in"
